### ISSUE TITLE
The GET button disappears, and refreshing a single image doesn't fix it

### ISSUE THREAD

**Issue by Qwerty-Space** [jbostrus/deviantart-gallery-ripper#1]

**Comment by jbostrus** [comment]
This should be resolved in a fashion with the latest push. There's caveats.

The get links button will no longer appear on single image pages. Only on the gallery page or pages the script thinks have a gallery. If you access the gallery then open an image and then go back it may not properly refresh and you may need to refresh the gallery page. This was due to changes on DA's side. The way it was trying to find the gallery link when looking at an image no longer works. So you have to manually go to the gallery for the user.
